[package]
name = "bomberman"
version = "0.1.0"
edition = "2021"

[dependencies]
debounced = "0.1.0"

tokio-tungstenite = "0.18.0"
tokio = { version = "1.28.1", features = ["full"] }
parking_lot = "0.12.1"
